language: emacs-lisp
env:
  - EMACS=emacs24 EMACS_REPO=cassou/emacs
  - EMACS=emacs-snapshot EMACS_REPO=ubuntu-elisp/ppa
before_install:
  - sudo add-apt-repository -y ppa:$EMACS_REPO
  - sudo apt-get update
  - sudo apt-get -y install $EMACS
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
install:
  - cask install
script:
  - cask exec ert-runner
  - cask exec ecukes
